name: Create feature branch

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  Create:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@master
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
