name: Generate Documentation

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  jsdocs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install

      - name: Generate
        run: |
          npm run docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
