name: New Repo Docs

on:
  issues:
    types: [ assigned ]

  workflow_dispatch:

jobs:

  Generate:

    runs-on: ubuntu-latest

    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@master
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.Create_Issue_Branch.outputs.branchName }}
          submodules: 'recursive'

      - name: Meta
        uses: varunsridharan/action-repository-meta@main
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render
        uses: varunsridharan/action-dynamic-readme@main
        with:
          FILES: |
            .conf/content/package_json/package.json.core.template=package.json
            .conf/content/ignores/default.gitignore=.gitignore
            .conf/content/md/README.md=README.md
            .conf/content/md/CODE_OF_CONDUCT.md=CODE_OF_CONDUCT.md
            .conf/content/md/CONTRIBUTING.md=CONTRIBUTING.md
            .conf/content/md/LICENSE=LICENSE
            .conf/content/md/SECURITY.md=SECURITY.md
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.Create_Issue_Branch.outputs.branchName }}
          force: true